version: '3.8'
services:
  db:
    image: postgres:latest  # or 'mysql:latest' for MySQL
    container_name: test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"  # Adjust for MySQL if needed
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/  # Scripts to initialize database and tables
